on:
    workflow_call:
        inputs:
            print:
                required: false
                default: 'Default Print'
                type: string

jobs:
    reusable_workflow_job:
        runs-on: ubuntu-latest
        steps:
          - name: Printing
            env:
                PRINT: ${{ inputs.print }}
            run: echo "Printing: $PRINT"
            shell: bash
