name: Call a reusable workflow

on:
    pull_request:
        branches:
          - main
    push:

jobs:
    call-workflow:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - uses: ./.github/workflows/reuseable.yml
